### ISSUE TITLE
get_json_response fails while the filter request returns no object

### ISSUE THREAD

**Issue by ghost** [eBayClassifiedsGroup/nsnitro#10]
if i run 
nitro_session_obj.get(self.auth_url + '/'.join(['lbvserver']) + '?' +('filter=ipv46:%s'%Vip)).get_json_response() 
passing a ip address that's not associated with a lbvserver on the NetScaler LB, it raises an error in json.loads.

Error: TypeError: sequence item 1: expected string, NoneType found

P.S: Am running this on NetScaler 9.3. with python 2.7. Can you check it on a NS 9.2 and confirm??

**Comment by favoretti** [comment]
Well, check before you pass to loads whether object you got back is
None. Easy fix.

Sent from a mobile device

On 16 jan. 2012, at 06:55, anand jeyahar
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
well. ..get_json_response() is a function inside nsnitro.. besides, the object is not none..it returns a dictionary {'errorcode':0,'some_str':'some_str'} .. Anyway, the fix needs to be in nsnitro.. will put it in when i have time to test it right..

**Comment by favoretti** [comment]
Can you add the object here? I'll see if I can patch it.

Sent from a mobile device

On 16 jan. 2012, at 09:45, anand jeyahar
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
object?? you mean the nitro_session_obj?? it's just an instance of nsnitro.NSNitro. so am just using the get() method from there...then 

result = nitro_session_obj.get(self.auth_url + '/'.join(['lbvserver']) + '?' +('filter=ipv46:%s'%Vip))
result.get_json_response() 

Should replicate the error.....

**Comment by favoretti** [comment]
I meant json response string :)
But I'll try to reproduce on my own.

Sent from a mobile device

On 16 jan. 2012, at 10:44, anand jeyahar
reply@reply.github.com
wrote:
