### ISSUE TITLE
nsnitro installation on windows.

### ISSUE THREAD

**Issue by ghost** [eBayClassifiedsGroup/nsnitro#11]
There's a linux-specific path setting in the setup.py  file. See mail below:

> Anand,
> 
> After made a change to setup.py, I am able to install nsnitro.py on windows, but the "path" should be dynamic depends on >os plateform.
>  data_files=[
>            #('/usr/bin', ['contrib/nsnitrocmd.py'])
>           ('C:\Python27', ['contrib/nsnitrocmd.py'])
>  ],
> 
> Thanks,
> 
> Peng

**Comment by favoretti** [comment]
Cool. Care to submit a pull request for this please? I'm not much of a
windows person :)

Sent from a mobile device

On 29 feb. 2012, at 07:06, anand jeyahar
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
Neither am i. But do have  a windows VM will see what i can do..

**Comment by favoretti** [comment]
Since there's no real animo for win-based stuff, closing this until better days.
