### ISSUE TITLE
NSNitro.logout is broken

### ISSUE THREAD

**Issue by codylane** [eBayClassifiedsGroup/nsnitro#25]
I have recently been testing out this library and it is very helpful so far.  I noticed an issue using basic authentication of HTTP that after logging in and then logging out, logouts do not happen.  

Here is an example code snippet that leaves sessions authenticated to our netscaler.  Eventually, if ran enough times will cause the netscaler to block further sessions from logging in, until the default session timeout is reached.

Please let em know if you would like me to also provide a packet capture.

This was tested against Netscaler 10.0, build 73.5.nc
Tested with python 2.6.7 and 2.7.2 and have similar results.
# !/usr/bin/env python2.6

import nsnitro
from nsnitro.nsnitro import *
from nsnitro.nsresources import *
import sys

session = NSNitro('1.2.3.4', 'nsroot', 'nsroot')
logged_in= session.login()
if logged_in:
    print "logged in"
else:
    print "failed to login"
    sys.exit(1)

msg= session.logout()
print "logging out: %s" %(msg['message'])
sys.exit(msg['errorcode'])

**Comment by codylane** [comment]
Was able to determine the root cause of the issue.  The logout() method in NSNitro was sending 'logout: {}' in the request header vs the JSON request.  I'll submit a patched version in a moment.

**Comment by codylane** [comment]
Forked, and submitted patch as pull request.  https://github.com/favoretti/nsnitro/pull/26

**Comment by favoretti** [comment]
I reckon we can close this one as well :)
