### ISSUE TITLE
login() error reporting broken

### ISSUE THREAD

**Issue by TheKat** [eBayClassifiedsGroup/nsnitro#27]
In the NSNitro.login() function is this:
raise NSNitroError("Error logging in!" + ue.message)

However ue.message contains nothing. It's empty. This gives fairly useless error messages. ie:
NSNitroError(Error logging in!)

This should be more similar to this:
raise NSNitroError("Error logging in! " + str(ue))
which causes the error to come back more usefully similar to:
NSNitroError(Error logging in! &lt;urlopen error [Errno 111] Connection refused&gt;)

**Comment by favoretti** [comment]
Thanks, pushed a fix.
