### ISSUE TITLE
RFC: Import all known NITRO API exceptions from the API documentation.

### ISSUE THREAD

**Issue by ndenev** [eBayClassifiedsGroup/nsnitro#43]
Hi,

I'm looking for comments on the following change that imports all of the known NITRO API errors documented as specific Nsnitro exceptions:
https://github.com/ndenev/nsnitro/commit/b1c1d7203fae1559973b0975263ee597670129b1

To ease maintenance of the huge list of exceptions (and actually to import them anyway) I've also created the following script that auto-generates them based on the HTML documentation available for the NITRO REST API : https://gist.github.com/ndenev/8784232

--Nikolay

**Comment by favoretti** [comment]
From a very quick glance - it's backwards-compatible, right? If so, I don't see any issues merging it, looks like a great job!

One concern though - currently exceptions handling isn't there yet, which means that we basically will need to integrate them all in places where they should actually be thrown.. Is it worth the effort? :)

**Comment by ndenev** [comment]
Currently my diff removes the old exceptions, which I plan to add back.

And for the actual handling, with this modification the "errorcode" in the response payload from the Netscaler will be parsed (even for non 200 codes) and based on it the proper exceptions will be raised.

**Comment by ndenev** [comment]
Actually the handling is "fixed" by other commit that I've created a pull request for a few days ago :
https://github.com/ndenev/nsnitro/commit/421cbc87c35392d90f199fcb39d9ab472f9f75f9

**Comment by ndenev** [comment]
I've just checked again and while my diff removes the current exceptions added by atopuzov@,
it still should be backwards compatible as they weren't actually raised (which is fixed in my pull request).

Other consumers of the library that catch NSNitroError will continue to work as all of the new exceptions inherit form it.

**Comment by atopuzov** [comment]
Looks good

**Comment by ndenev** [comment]
Merged everything from the previous pull request and my changes from the exceptions branch to this pull request : https://github.com/favoretti/nsnitro/pull/44

**Comment by favoretti** [comment]
I guess we can close this one? #44 has been merged.

**Comment by ndenev** [comment]
Yup, closing.
