### ISSUE TITLE
Incorrect filename in Debian copyright

### ISSUE THREAD

**Issue by hyandell** [eBayClassifiedsGroup/nsnitro#46]
Noting that the Debian GPLv2 copyright file has a link to:

/usr/share/common-licenses/GPL-3

instead of:

/usr/share/common-licenses/GPL-2

Looks like a typo.

**Comment by favoretti** [comment]
What do you mean? I don't see any typo's there:

```
 [17][00:32:16] vlazarenko@alluminium (~/nsnitro) > grep -r "GPL-2" *
 [18][00:32:25] vlazarenko@alluminium (~/nsnitro) > grep -r "GPL-3" *
 debian/copyright:Public License can be found in `/usr/share/common-licenses/GPL-3'.
```

**Comment by favoretti** [comment]
Nevermind, I got what you meant. Kinda slow tonight.. Fixed.

**Comment by hyandell** [comment]
Thanks Vladimir :)
