### ISSUE TITLE
New pypi release?

### ISSUE THREAD

**Issue by favoretti** [eBayClassifiedsGroup/nsnitro#48]
Should I push a new pypi release? Or are most of you building this by yourselves?

**Comment by al4** [comment]
A pypi release would be very useful for me personally. Our deployer is built with dh_virtualenv and it pulls its dependencies from pip.

**Comment by favoretti** [comment]
Submitting dist/nsnitro-1.0.26.tar.gz to http://pypi.python.org/pypi
Server response (200): OK
Submitting /Users/vlazarenko/nsnitro/dist/nsnitro-1.0.26.macosx-10.9-intel.tar.gz to http://pypi.python.org/pypi
Server response (200): OK

**Comment by favoretti** [comment]
Ehh, version bump would have been nice too.. So...

running upload
Submitting dist/nsnitro-1.0.27.tar.gz to http://pypi.python.org/pypi
Server response (200): OK
Submitting /Users/vlazarenko/nsnitro/dist/nsnitro-1.0.27.macosx-10.9-intel.tar.gz to http://pypi.python.org/pypi
Server response (200): OK

**Comment by al4** [comment]
Thanks!
