### ISSUE TITLE
namespace_packages in setup.py interferes with pip installation

### ISSUE THREAD

**Issue by vortura** [eBayClassifiedsGroup/nsnitro#67]
Hi, this is not so much an issue as a question - What's the preferred way to install this module? The reason I ask is that when installed with `pip install nsnitro`, the usage examples don't work. e.g.

```
richard at snowden in ~/Dropbox/projects/test
(test) $ pip install nsnitro
Downloading/unpacking nsnitro
... snip ...
Skipping installation of /Users/richard/lib/virtualenvs/test/lib/python2.7/site-packages/nsnitro/__init__.py (namespace package)
... snip ...
```

Because nsnitro is a namespace package, pip ignores the contents of `__init__.py`, meaning the imports don't quite work as described. i.e. instead of `from nsnitro import *`, you need to use `from nsnitro.nsnitro import *` or `from nsnitro import nsnitro`, etc.

I'd be happy to submit a pull request to fix either setup.py or the documentation, but I figured I'd check I'm installing the module correctly first. It seems to me that there's little value in using a namespace package here, but I guess the problem is you may now have users depending on this import behaviour.

So, am I doing it wrong?

**Comment by favoretti** [comment]
To be honest back in the days I wrote setup.py I didn't really wrap my brain around the whole concept of namespace packages, so I just did something that seemed to work. 

Fixing it in a proper way is most welcome I'd say. 

And then again, I guess if we remove the fact that it's a namespace package, it won't break `from nsnitro.nsnitro import *` type of imports, right? (I'm still a bit clueless about this, I'm sorry)

**Comment by vortura** [comment]
I have to admit I don't know a great deal about namespace packages either, but it doesn't seem to add anything for this particular module, and messes with pip installation slightly.

Have a look at that pull request and see what you think. The existing `from nsnitro.nsnitro import *` import behaviour is preserved, while also allowing the more concise `from nsnitro import *`.

**Comment by favoretti** [comment]
Merged pull request.
