### ISSUE TITLE
lbvserverservicebinding class redundant

### ISSUE THREAD

**Issue by ghost** [eBayClassifiedsGroup/nsnitro#7]
concept of binding class for lbvserverservcie doesn't make sense.. can just use a basebinding class.. The name field is meaningless in this class and therefore the get_name has to be replaced...
Also the

**Comment by favoretti** [comment]
Umm, how come is name meaningless in this class? That's one of the classes we use the most atm, so I'm curious as to your point of view. We could try and extrapolate basebinding, if there is anything to basebind :)

**Comment by ghost** [comment]
Umm.. i realized that binding not being a baseresource it's identified by servicegroup,service and server(vserver or otherwise). call it composite key if you will. so at best having a field/attribute name is misleading......

**Comment by ghost** [comment]
Am not clear about the Base bind yet.. that was just a hasty first idea.... Look at it from Data modeling viewpoint... and binding is not a base resource but a linker resource.. or an intermediary class/table to maintain mapping between two different tables. ...

**Comment by favoretti** [comment]
It is indeed a linker resource. In this case, if my memory serves me right 'name' is vserver name that needs to be bound to the service. Can't make it better for you, as that's how the JSON is defined on the side of netscaler unfortunately. There are quire a few choices in their API that could have been made much easier, but oh well :)

**Comment by ghost** [comment]
//here are quire a few choices in their API that could have been made much easier,
Hmm.... True...i feel the same too.. 
Just tested it.. name can be either vserver or server... but that doesn't solve the problem...  Will let this issue stay open over the weekend, in case inspiration strikes :-) and close it on monday

**Comment by favoretti** [comment]
What's the problem you're having? You're trying to bind a service to a servicegroup?

**Comment by ghost** [comment]
Problem?? Oh...I was just referring to binding class deriving from baseresource and then using the name attribute for vserver/server attribute......
Sorry for the confusion
