### ISSUE TITLE
bug in lbvserver servicebinding

### ISSUE THREAD

**Issue by ghost** [eBayClassifiedsGroup/nsnitro#8]
I am passing weight value in the following code and still says weight value is missing... Might be a nitro error itself..

<code>
from nsnitro.nsresources.nslbvserverservicebinding import NSLBVServerServiceBinding
from nsnitro.nsnitro import NSNitro
random_vip = '192.168.8.153'
sg = { 'servicegroupname':"Test-SG-%s"%random_vip,
                      'name':"Test-lbvserver-%s"%random_vip,
                      'weight':20
                    }
nitro_session_obj = NSNitro("10.11.254.30","ddosadmin","ddosAdmin")
nitro_session_obj.login()
lbbinding = NSLBVServerServiceBinding(sg)
print NSLBVServerServiceBinding.add(nitro_session_obj,lbbinding)

</code>

gives error:
<code>
Traceback (most recent call last):
  File "../ex.py", line 18, in <module>
    print NSLBVServerServiceBinding.add(nitro_session_obj,lbbinding)
  File "/usr/local/lib/python2.7/dist-packages/nsnitro-1.0.6-py2.7.egg/nsnitro/nsresources/nslbvserverservicebinding.py", line 179, in add
    return __vserver_service_binding.update_resource(nitro)
  File "/usr/local/lib/python2.7/dist-packages/nsnitro-1.0.6-py2.7.egg/nsresources/nsbaseresource.py", line 80, in update_resource
    response = nitro.put(self.get_put_payload(nitro.get_sessionid()))
  File "/usr/local/lib/python2.7/dist-packages/nsnitro-1.0.6-py2.7.egg/nsnitro/nsnitro.py", line 92, in put
    raise NSNitroError(nsresponse.message)
nsnitro.nsutil.NSNitroError: u'Argument pre-requisite missing [weight, serviceName]'

</code>

Also if i pass both servicegroup and service both, it would be nice to have the python class raise an error before connecting and trying on the NetScaler...

**Comment by favoretti** [comment]
I think it's complaining because servicename is missing, not weight. It seems servicename is required.

**Comment by ghost** [comment]
On the contrary, when tried giving a servicename it gave me an error saying servicename and servicegroupname both cannot be given...

**Comment by ghost** [comment]
<code>
from nsnitro.nsresources.nslbvserverservicebinding import NSLBVServerServiceBinding
from nsnitro.nsnitro import NSNitro

random_vip = '192.168.8.153'
sg = { 'servicegroupname':"Test-SG-%s"%random_vip,
       'name':"Test-lbvserver-%s"%random_vip,
       'weight':20,

```
  'servicename':'http' 
                }
```

nitro_session_obj = NSNitro("10.11.254.30","ddosadmin","ddosAdmin")
nitro_session_obj.login()
lbbinding = NSLBVServerServiceBinding(sg)
print NSLBVServerServiceBinding.add(nitro_session_obj,lbbinding)

</code>

<code>
Traceback (most recent call last):
  File "../ex.py", line 19, in <module>
    print NSLBVServerServiceBinding.add(nitro_session_obj,lbbinding)
  File "/usr/local/lib/python2.7/dist-packages/nsnitro-1.0.6-py2.7.egg/nsnitro/nsresources/nslbvserverservicebinding.py", line 179, in add
    return __vserver_service_binding.update_resource(nitro)
  File "/usr/local/lib/python2.7/dist-packages/nsnitro-1.0.6-py2.7.egg/nsresources/nsbaseresource.py", line 80, in update_resource
    response = nitro.put(self.get_put_payload(nitro.get_sessionid()))
  File "/usr/local/lib/python2.7/dist-packages/nsnitro-1.0.6-py2.7.egg/nsnitro/nsnitro.py", line 92, in put
    raise NSNitroError(nsresponse.message)
nsnitro.nsutil.NSNitroError: u'Arguments cannot both be specified [serviceGroupName, serviceName]'

</code>

**Comment by ghost** [comment]
Am pretty sure\* this is more due to some hidden/undocumented link between servicegroup and service ...But can't seem to find it on the NetScaler Documentation...

*-- because the names hint at something..

**Comment by ghost** [comment]
Hi, can you confirm you can replicate this ? perhaps on the 9.2 LB??

**Comment by favoretti** [comment]
Haven't had the time yet. Will try.

Sent from a mobile device

On 4 jan. 2012, at 17:09, anand jeyahar
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
thanks.. ok..

**Comment by ghost** [comment]
Citrix it's not supported in NetScaler 9.3 .. will close the issue.

**Comment by ghost** [comment]
Refer citrix Support Request: SR 60689911
