### ISSUE TITLE
moving a servicegroup from one lb to another

### ISSUE THREAD

**Issue by ghost** [eBayClassifiedsGroup/nsnitro#9]
Hi,
  If i retrieve a servicegroup using filter by name from a LB and pass the first obj of the resulting list to create servicegroup call, it creates a servicegroup with a blank name <more likely some invisible chars>. Clearly, there's something going wrong with unicode string handling/conversion.

**Comment by favoretti** [comment]
Hum, did you add filters to the base object? :) If so, can I have a pull request? :)

**Comment by ghost** [comment]
No, i haven't am just handcrafting the filter request at the moment.. and running under tight schedule.. so won't try for a couple of weeks...
