### ISSUE TITLE
add server nsnitrocmd.py

### ISSUE THREAD

**Issue by marcosartori** [eBayClassifiedsGroup/nsnitro#97]
Hi, thanks for this its really helping me out.  However unless I have missed something (which I might of) I cannot seem to add a server, which I need to do as I then want to bind it to a service group, that is using nsnitrocmd.py.

I can see however that is supported from the api, so I have most likely horribly added an add server option

```
usage: nsnitrocmd.py IP addserver [-h] SERVER SERVERIP

positional arguments:
  SERVER      name of server to add
  SERVERIP    the server IP address

```

woud you be interested in a pull, or have I missed this feature already.

thanks again.

**Comment by favoretti** [comment]
Hey,

Of course, we're always interested in a pull.
That being said, Citrix released an official SDK, sadly, not completely compatible with this one. So if you're just starting you might wanna have a look at it as well.

Regards,
Vlad
